import type { Engagement, Opening, Project, PromptOpportunity } from "./types";

export const demoProject: Project = {
  id: "proj_attio_demo",
  name: "Attio — AI search visibility",
  ownBrand: { name: "Attio", domain: "attio.com" },
  competitors: [
    { name: "HubSpot", domain: "hubspot.com" },
    { name: "Salesforce", domain: "salesforce.com" },
    { name: "Airtable", domain: "airtable.com" },
  ],
  models: ["ChatGPT", "Perplexity", "Gemini", "Google AI Overviews", "Claude"],
  promptCount: 24,
  lastSyncedAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
};

export const demoPrompts: PromptOpportunity[] = [
  {
    id: "p1",
    text: "HubSpot alternatives for startups",
    ownVisibility: 8,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 72,
    visibilityGap: -64,
    sourcesFound: 9,
    hiddenQuestionsFound: 6,
    openingsFound: 5,
    opportunityScore: 94,
    status: "best_opportunity",
    reasons: [
      "You are losing badly to HubSpot.",
      "AI already reads sources where your brand could naturally appear.",
      "The prompt has multiple QFOs we can target.",
      "There are safe engagement openings available today.",
    ],
    hiddenQuestions: [
      "Best CRM for early-stage startups",
      "Cheaper alternative to HubSpot",
      "CRM with flexible data model",
      "CRM for founder-led sales",
      "Modern CRM that isn't HubSpot",
      "Lightweight CRM for under 20 people",
    ],
    competitorBreakdown: [
      { brand: "HubSpot", visibility: 72 },
      { brand: "Salesforce", visibility: 41 },
      { brand: "Pipedrive", visibility: 28 },
      { brand: "Attio", visibility: 8 },
    ],
  },
  {
    id: "p2",
    text: "best CRM for startups",
    ownVisibility: 14,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 64,
    visibilityGap: -50,
    sourcesFound: 11,
    hiddenQuestionsFound: 5,
    openingsFound: 4,
    opportunityScore: 88,
    status: "critical_gap",
  },
  {
    id: "p3",
    text: "CRM with flexible data model",
    ownVisibility: 31,
    topCompetitor: "Airtable",
    topCompetitorVisibility: 44,
    visibilityGap: -13,
    sourcesFound: 6,
    hiddenQuestionsFound: 4,
    openingsFound: 3,
    opportunityScore: 76,
    status: "quick_win",
  },
  {
    id: "p4",
    text: "Salesforce alternatives for small teams",
    ownVisibility: 11,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 58,
    visibilityGap: -47,
    sourcesFound: 8,
    hiddenQuestionsFound: 4,
    openingsFound: 3,
    opportunityScore: 81,
    status: "high_impact",
  },
  {
    id: "p5",
    text: "best CRM for founder-led sales",
    ownVisibility: 22,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 49,
    visibilityGap: -27,
    sourcesFound: 7,
    hiddenQuestionsFound: 3,
    openingsFound: 3,
    opportunityScore: 72,
    status: "high_impact",
  },
  {
    id: "p6",
    text: "best modern CRM",
    ownVisibility: 19,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 51,
    visibilityGap: -32,
    sourcesFound: 9,
    hiddenQuestionsFound: 4,
    openingsFound: 2,
    opportunityScore: 68,
    status: "high_impact",
  },
  {
    id: "p7",
    text: "Attio review",
    ownVisibility: 78,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 12,
    visibilityGap: 66,
    sourcesFound: 5,
    hiddenQuestionsFound: 2,
    openingsFound: 1,
    opportunityScore: 24,
    status: "already_strong",
  },
  {
    id: "p8",
    text: "CRM pricing comparison",
    ownVisibility: 6,
    topCompetitor: "HubSpot",
    topCompetitorVisibility: 38,
    visibilityGap: -32,
    sourcesFound: 4,
    hiddenQuestionsFound: 2,
    openingsFound: 1,
    opportunityScore: 41,
    status: "low_priority",
  },
];

export const demoOpenings: Opening[] = [
  {
    id: "o1",
    promptId: "p1",
    sourceName: "Reddit r/SaaS — Best CRM for early-stage startups",
    sourceUrl: "https://reddit.com/r/SaaS/comments/best-crm-startups",
    sourceType: "Community discussion",
    influencedQuestions: [
      "HubSpot alternatives for startups",
      "CRM with flexible data model",
      "CRM for founder-led sales",
    ],
    brandMentions: { HubSpot: 14, Salesforce: 6, Airtable: 5, Attio: 0 },
    ownBrandPresent: false,
    competitorPresent: true,
    openingType: "Reddit comment opportunity",
    impactScore: 91,
    riskLevel: "medium",
    status: "ready",
    whyItMatters:
      "This thread is cited across 3 hidden questions and contains direct founder opinions that AI engines repeatedly retrieve.",
    missingProof:
      "No one explains Attio as the flexible CRM for fast-changing startup workflows.",
    recommendedEngagement:
      "Post a transparent, helpful comment comparing when HubSpot works and when a flexible CRM data model matters.",
    citationCount: 23,
    retrievalCount: 41,
    citationRate: 0.56,
    domainInfluence: 92,
    painSignals: [
      "HubSpot gets expensive",
      "Salesforce is overkill",
      "Airtable is flexible but not a real CRM",
      "We need something lightweight but structured",
    ],
    repeatedClaims: [
      "HubSpot is the default but you outgrow the price",
      "Founders want pipelines that bend, not templates",
    ],
  },
  {
    id: "o2",
    promptId: "p1",
    sourceName: "SaaSGenius — 12 Best CRMs for Startups in 2026",
    sourceUrl: "https://saasgenius.example/best-crms-startups",
    sourceType: "Editorial listicle",
    influencedQuestions: [
      "best CRM for startups",
      "Salesforce alternatives for small teams",
    ],
    brandMentions: { HubSpot: 8, Salesforce: 7, Pipedrive: 4, Attio: 0 },
    ownBrandPresent: false,
    competitorPresent: true,
    openingType: "Blog/editorial update pitch",
    impactScore: 88,
    riskLevel: "low",
    status: "ready",
    whyItMatters:
      "Cited in Perplexity and Google AI Overviews for 4 high-intent prompts. Updates to this article propagate within ~10 days.",
    missingProof:
      "No mention of flexible relationship models — the angle missing from every listicle.",
    recommendedEngagement:
      "Pitch the editor a section on 'Flexible CRMs for fast-changing startup workflows' with two real customer examples.",
    citationCount: 17,
    retrievalCount: 29,
    citationRate: 0.59,
    domainInfluence: 81,
    painSignals: [
      "Templates feel rigid",
      "Hard to model partners + investors + customers in one CRM",
    ],
  },
  {
    id: "o3",
    promptId: "p1",
    sourceName: "G2 — CRM category page",
    sourceUrl: "https://g2.com/categories/crm",
    sourceType: "Review site",
    influencedQuestions: [
      "best CRM for early-stage startups",
      "HubSpot alternatives",
    ],
    brandMentions: { HubSpot: 21, Salesforce: 18, Attio: 2 },
    ownBrandPresent: true,
    competitorPresent: true,
    openingType: "Review request campaign",
    impactScore: 84,
    riskLevel: "low",
    status: "needs_input",
    whyItMatters:
      "G2 is the second most-cited domain across CRM prompts. Review density directly correlates with AI mention rate.",
    missingProof:
      "Only 2 Attio reviews surface near the top. Need 25+ recent reviews from founder-led teams.",
    recommendedEngagement:
      "Run a 14-day review campaign targeting design partners and recent customers. Provide a one-click template.",
    citationCount: 31,
    retrievalCount: 58,
    citationRate: 0.53,
    domainInfluence: 88,
  },
  {
    id: "o4",
    promptId: "p1",
    sourceName: "YouTube — 'I tried 6 CRMs so you don't have to'",
    sourceUrl: "https://youtube.com/watch?v=crm-roundup",
    sourceType: "Video / comments",
    influencedQuestions: ["CRM with flexible data model"],
    brandMentions: { HubSpot: 9, Pipedrive: 5, Attio: 0 },
    ownBrandPresent: false,
    competitorPresent: true,
    openingType: "YouTube creator pitch",
    impactScore: 77,
    riskLevel: "low",
    status: "ready",
    whyItMatters:
      "Transcript is cited by Gemini for visual product comparisons. Comments section feeds the retrieval index.",
    missingProof: "No demo of Attio's flexible objects in the video.",
    recommendedEngagement:
      "Pitch the creator a follow-up segment + post a useful, disclosed top-comment with a link to a free template.",
    citationCount: 9,
    retrievalCount: 14,
    citationRate: 0.64,
    domainInfluence: 73,
  },
  {
    id: "o5",
    promptId: "p1",
    sourceName: "Wikipedia — Customer relationship management",
    sourceUrl: "https://en.wikipedia.org/wiki/Customer_relationship_management",
    sourceType: "Reference source",
    influencedQuestions: ["best CRM for startups"],
    brandMentions: { HubSpot: 4, Salesforce: 12, Attio: 0 },
    ownBrandPresent: false,
    competitorPresent: true,
    openingType: "Blocked: unsafe source action",
    impactScore: 70,
    riskLevel: "high",
    status: "blocked",
    whyItMatters:
      "Wikipedia is one of the most heavily retrieved sources, but enforces strict notability and neutrality rules.",
    missingProof: "Attio does not yet meet Wikipedia notability thresholds.",
    recommendedEngagement:
      "Build independent third-party evidence (TechCrunch, The Information, academic refs) before any edit.",
    blockedReason:
      "Wikipedia requires neutrality and notability. Direct edits would be reverted and could harm domain trust. Safer action: build independent third-party evidence first.",
    citationCount: 44,
    retrievalCount: 71,
    citationRate: 0.62,
    domainInfluence: 99,
  },
];

export const demoEngagements: Engagement[] = [
  {
    id: "e1",
    openingId: "o1",
    title: "Helpful Reddit comment — when a flexible CRM actually wins",
    format: "comment",
    draft:
      "I work with Attio, so take this with context. For early-stage teams, I'd usually split this decision into two questions: do you need a simple pipeline, or do you need a flexible relationship model that changes every few weeks?\n\nHubSpot is strong if you want templates and a standard GTM motion. Where teams often struggle is when accounts, investors, partners, and customers overlap, and the CRM needs to behave more like a flexible workspace than a fixed pipeline. That's the kind of use case where a flexible CRM like Attio becomes worth looking at.\n\nHappy to share what we've seen work and where it doesn't if useful.",
    targetQuestions: [
      "HubSpot alternatives for startups",
      "CRM with flexible data model",
    ],
    targetSource: "reddit.com/r/SaaS",
    missingProofAddressed:
      "Explains when a flexible relationship model beats a fixed pipeline.",
    disclosure: "I work with Attio",
    qualityChecks: [
      { label: "Disclosure included", status: "pass", note: "Discloses affiliation up front." },
      { label: "Helpful, not spammy", status: "pass", note: "Frames trade-offs before mentioning brand." },
      { label: "Evidence-backed", status: "warning", note: "Add one real customer example." },
      { label: "Source fit", status: "pass", note: "Matches r/SaaS norms." },
      { label: "Anti-slop score", status: "pass", note: "92 / 100" },
      { label: "Self-promo risk", status: "warning", note: "Medium — keep tone consultative." },
    ],
    status: "draft",
  },
  {
    id: "e2",
    openingId: "o2",
    title: "Editorial pitch — flexible CRMs for fast-changing startup workflows",
    format: "pitch_email",
    draft:
      "Hi {{editor_name}},\n\nI noticed your CRM comparison article is being referenced in discussions around startup CRM alternatives — nice work.\n\nOne angle that seems underrepresented across the category is the shift from fixed pipeline CRMs to flexible relationship models for early-stage teams. Several founder discussions mention that HubSpot becomes expensive past a certain seat count, Salesforce feels too heavy for sub-20-person teams, and Airtable is flexible but not CRM-native.\n\nWould you be open to considering a short section on 'Flexible CRMs for fast-changing startup workflows'? I can share two customer examples and original screenshots — no link required if it doesn't fit editorially.\n\nThanks either way,\n{{your_name}}",
    targetQuestions: ["best CRM for startups", "Salesforce alternatives for small teams"],
    targetSource: "saasgenius.example",
    missingProofAddressed: "Adds the missing 'flexible relationship model' angle.",
    qualityChecks: [
      { label: "Tone fit", status: "pass", note: "Matches editorial outreach norms." },
      { label: "Specific value", status: "pass", note: "Offers angle + assets, not just a backlink." },
      { label: "No demand for link", status: "pass", note: "Editor can decline gracefully." },
    ],
    status: "draft",
  },
  {
    id: "e3",
    openingId: "o3",
    title: "G2 review request campaign — 14-day plan",
    format: "review_brief",
    draft:
      "GOAL: 25+ recent G2 reviews from founder-led teams within 14 days.\n\nSEGMENT: Customers who joined in the last 6 months and have shipped 3+ workflows in Attio.\n\nMESSAGE TEMPLATE: A short, personal email from a founder thanking them and asking for a 5-min review with three guiding prompts (data model, time-to-value, what made you switch).\n\nSAFETY: No incentives tied to a specific rating. Disclose the founder ask. Track completion via UTM only.",
    targetQuestions: ["best CRM for early-stage startups", "HubSpot alternatives"],
    targetSource: "g2.com",
    missingProofAddressed: "Increases recent review density on G2's CRM page.",
    qualityChecks: [
      { label: "G2 policy compliant", status: "pass", note: "No rating-conditional incentives." },
      { label: "Realistic volume", status: "pass", note: "Based on active customer cohort size." },
      { label: "Customer list ready", status: "fail", note: "Needs export from CRM." },
    ],
    status: "draft",
  },
  {
    id: "e4",
    openingId: "o4",
    title: "YouTube creator pitch + helpful top comment",
    format: "creator_pitch",
    draft:
      "PITCH (DM): Loved the roundup. Would you be open to a 5-minute follow-up clip on flexible-object CRMs? Happy to send a sandbox + script outline.\n\nCOMMENT (disclosed): Great breakdown. One thing I'd add — for teams whose data model changes a lot (investors, partners, candidates living in the same CRM), flexible-object CRMs like Attio (disclosure: I work there) can save a lot of glue work compared to template-heavy tools. Free template in the description if helpful.",
    targetQuestions: ["CRM with flexible data model"],
    targetSource: "youtube.com",
    missingProofAddressed: "Demonstrates flexible objects in a creator's existing audience.",
    qualityChecks: [
      { label: "Disclosure included", status: "pass", note: "Comment discloses affiliation." },
      { label: "Adds value", status: "pass", note: "Provides a usable template." },
    ],
    status: "draft",
  },
  {
    id: "e5",
    openingId: "o5",
    title: "Blocked — Wikipedia edit",
    format: "comment",
    draft:
      "BLOCKED. Wikipedia requires independent, non-promotional secondary sources. Recommended path: secure 2–3 independent feature articles in Tier-1 publications (TechCrunch, The Information, Sifted) over the next quarter, then revisit notability.",
    targetQuestions: ["best CRM for startups"],
    targetSource: "en.wikipedia.org",
    missingProofAddressed: "—",
    qualityChecks: [
      { label: "Policy compliance", status: "fail", note: "Notability + neutrality not yet met." },
    ],
    status: "blocked",
  },
];
