/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskIdRouteImport } from './routes/task.$id'
import { Route as QueueDraftIdRouteImport } from './routes/queue.draft.$id'
import { Route as ApiTavilyExtractRouteImport } from './routes/api/tavily/extract'
import { Route as ApiPublicBulkScrapeRouteImport } from './routes/api/public/bulk-scrape'
import { Route as ApiPublicAnalyzePromptRouteImport } from './routes/api/public/analyze-prompt'
import { Route as ApiPeecToolRouteImport } from './routes/api/peec.$tool'
import { Route as ApiAgentsGenerateEngagementsRouteImport } from './routes/api/agents/generate-engagements'
import { Route as ApiAgentsFindOpeningsRouteImport } from './routes/api/agents/find-openings'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIdRoute = TaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueDraftIdRoute = QueueDraftIdRouteImport.update({
  id: '/draft/$id',
  path: '/draft/$id',
  getParentRoute: () => QueueRoute,
} as any)
const ApiTavilyExtractRoute = ApiTavilyExtractRouteImport.update({
  id: '/api/tavily/extract',
  path: '/api/tavily/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBulkScrapeRoute = ApiPublicBulkScrapeRouteImport.update({
  id: '/api/public/bulk-scrape',
  path: '/api/public/bulk-scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzePromptRoute = ApiPublicAnalyzePromptRouteImport.update({
  id: '/api/public/analyze-prompt',
  path: '/api/public/analyze-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeecToolRoute = ApiPeecToolRouteImport.update({
  id: '/api/peec/$tool',
  path: '/api/peec/$tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsGenerateEngagementsRoute =
  ApiAgentsGenerateEngagementsRouteImport.update({
    id: '/api/agents/generate-engagements',
    path: '/api/agents/generate-engagements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentsFindOpeningsRoute = ApiAgentsFindOpeningsRouteImport.update({
  id: '/api/agents/find-openings',
  path: '/api/agents/find-openings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/openings': typeof OpeningsRoute
  '/prompts': typeof PromptsRoute
  '/queue': typeof QueueRouteWithChildren
  '/results': typeof ResultsRoute
  '/studio': typeof StudioRoute
  '/task/$id': typeof TaskIdRoute
  '/api/agents/find-openings': typeof ApiAgentsFindOpeningsRoute
  '/api/agents/generate-engagements': typeof ApiAgentsGenerateEngagementsRoute
  '/api/peec/$tool': typeof ApiPeecToolRoute
  '/api/public/analyze-prompt': typeof ApiPublicAnalyzePromptRoute
  '/api/public/bulk-scrape': typeof ApiPublicBulkScrapeRoute
  '/api/tavily/extract': typeof ApiTavilyExtractRoute
  '/queue/draft/$id': typeof QueueDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/openings': typeof OpeningsRoute
  '/prompts': typeof PromptsRoute
  '/queue': typeof QueueRouteWithChildren
  '/results': typeof ResultsRoute
  '/studio': typeof StudioRoute
  '/task/$id': typeof TaskIdRoute
  '/api/agents/find-openings': typeof ApiAgentsFindOpeningsRoute
  '/api/agents/generate-engagements': typeof ApiAgentsGenerateEngagementsRoute
  '/api/peec/$tool': typeof ApiPeecToolRoute
  '/api/public/analyze-prompt': typeof ApiPublicAnalyzePromptRoute
  '/api/public/bulk-scrape': typeof ApiPublicBulkScrapeRoute
  '/api/tavily/extract': typeof ApiTavilyExtractRoute
  '/queue/draft/$id': typeof QueueDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/openings': typeof OpeningsRoute
  '/prompts': typeof PromptsRoute
  '/queue': typeof QueueRouteWithChildren
  '/results': typeof ResultsRoute
  '/studio': typeof StudioRoute
  '/task/$id': typeof TaskIdRoute
  '/api/agents/find-openings': typeof ApiAgentsFindOpeningsRoute
  '/api/agents/generate-engagements': typeof ApiAgentsGenerateEngagementsRoute
  '/api/peec/$tool': typeof ApiPeecToolRoute
  '/api/public/analyze-prompt': typeof ApiPublicAnalyzePromptRoute
  '/api/public/bulk-scrape': typeof ApiPublicBulkScrapeRoute
  '/api/tavily/extract': typeof ApiTavilyExtractRoute
  '/queue/draft/$id': typeof QueueDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/openings'
    | '/prompts'
    | '/queue'
    | '/results'
    | '/studio'
    | '/task/$id'
    | '/api/agents/find-openings'
    | '/api/agents/generate-engagements'
    | '/api/peec/$tool'
    | '/api/public/analyze-prompt'
    | '/api/public/bulk-scrape'
    | '/api/tavily/extract'
    | '/queue/draft/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/openings'
    | '/prompts'
    | '/queue'
    | '/results'
    | '/studio'
    | '/task/$id'
    | '/api/agents/find-openings'
    | '/api/agents/generate-engagements'
    | '/api/peec/$tool'
    | '/api/public/analyze-prompt'
    | '/api/public/bulk-scrape'
    | '/api/tavily/extract'
    | '/queue/draft/$id'
  id:
    | '__root__'
    | '/'
    | '/openings'
    | '/prompts'
    | '/queue'
    | '/results'
    | '/studio'
    | '/task/$id'
    | '/api/agents/find-openings'
    | '/api/agents/generate-engagements'
    | '/api/peec/$tool'
    | '/api/public/analyze-prompt'
    | '/api/public/bulk-scrape'
    | '/api/tavily/extract'
    | '/queue/draft/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpeningsRoute: typeof OpeningsRoute
  PromptsRoute: typeof PromptsRoute
  QueueRoute: typeof QueueRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  StudioRoute: typeof StudioRoute
  TaskIdRoute: typeof TaskIdRoute
  ApiAgentsFindOpeningsRoute: typeof ApiAgentsFindOpeningsRoute
  ApiAgentsGenerateEngagementsRoute: typeof ApiAgentsGenerateEngagementsRoute
  ApiPeecToolRoute: typeof ApiPeecToolRoute
  ApiPublicAnalyzePromptRoute: typeof ApiPublicAnalyzePromptRoute
  ApiPublicBulkScrapeRoute: typeof ApiPublicBulkScrapeRoute
  ApiTavilyExtractRoute: typeof ApiTavilyExtractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$id': {
      id: '/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof TaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/draft/$id': {
      id: '/queue/draft/$id'
      path: '/draft/$id'
      fullPath: '/queue/draft/$id'
      preLoaderRoute: typeof QueueDraftIdRouteImport
      parentRoute: typeof QueueRoute
    }
    '/api/tavily/extract': {
      id: '/api/tavily/extract'
      path: '/api/tavily/extract'
      fullPath: '/api/tavily/extract'
      preLoaderRoute: typeof ApiTavilyExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bulk-scrape': {
      id: '/api/public/bulk-scrape'
      path: '/api/public/bulk-scrape'
      fullPath: '/api/public/bulk-scrape'
      preLoaderRoute: typeof ApiPublicBulkScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-prompt': {
      id: '/api/public/analyze-prompt'
      path: '/api/public/analyze-prompt'
      fullPath: '/api/public/analyze-prompt'
      preLoaderRoute: typeof ApiPublicAnalyzePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peec/$tool': {
      id: '/api/peec/$tool'
      path: '/api/peec/$tool'
      fullPath: '/api/peec/$tool'
      preLoaderRoute: typeof ApiPeecToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/generate-engagements': {
      id: '/api/agents/generate-engagements'
      path: '/api/agents/generate-engagements'
      fullPath: '/api/agents/generate-engagements'
      preLoaderRoute: typeof ApiAgentsGenerateEngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/find-openings': {
      id: '/api/agents/find-openings'
      path: '/api/agents/find-openings'
      fullPath: '/api/agents/find-openings'
      preLoaderRoute: typeof ApiAgentsFindOpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QueueRouteChildren {
  QueueDraftIdRoute: typeof QueueDraftIdRoute
}

const QueueRouteChildren: QueueRouteChildren = {
  QueueDraftIdRoute: QueueDraftIdRoute,
}

const QueueRouteWithChildren = QueueRoute._addFileChildren(QueueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpeningsRoute: OpeningsRoute,
  PromptsRoute: PromptsRoute,
  QueueRoute: QueueRouteWithChildren,
  ResultsRoute: ResultsRoute,
  StudioRoute: StudioRoute,
  TaskIdRoute: TaskIdRoute,
  ApiAgentsFindOpeningsRoute: ApiAgentsFindOpeningsRoute,
  ApiAgentsGenerateEngagementsRoute: ApiAgentsGenerateEngagementsRoute,
  ApiPeecToolRoute: ApiPeecToolRoute,
  ApiPublicAnalyzePromptRoute: ApiPublicAnalyzePromptRoute,
  ApiPublicBulkScrapeRoute: ApiPublicBulkScrapeRoute,
  ApiTavilyExtractRoute: ApiTavilyExtractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
